### PR TITLE
Fix event persistence error handling

### LINKED ISSUE #48: Build did not fail despite SQL exception
The build process did not detect and fail due to a SQL exception caused by a syntax error in the telemetry insert query (error stack below)

```
java.sql.SQLException: java.sql.SQLException: Parser Error: syntax error at or near "a"
LINE 4:     VALUES (adc736...
                                ^
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:117) ~[duckdb_jdbc-0.8.0.jar:?]
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:185) ~[duckdb_jdbc-0.8.0.jar:?]
	at com.microsoft.lst_bench.telemetry.JDBCTelemetryRegistry.flush(JDBCTelemetryRegistry.java:107) ~[classes/:?]
	at com.microsoft.lst_bench.common.LSTBenchmarkExecutor.execute(LSTBenchmarkExecutor.java:128) ~[classes/:?]
	at com.microsoft.lst_bench.Driver.main(Driver.java:147) ~[classes/:?]
	at com.microsoft.lst_bench.DriverSparkTest.testTPCDSW0Delta(DriverSparkTest.java:28) ~[test-classes/:?]
```

### PR DESCRIPTION
**Pull request by ashvina**
This commit fixes a bug in the error handling logic while attempting to flush event info objects. Currently, if an error occurs while persisting the events, the exception is caught, logged, and ignored. The error is not passed to the caller. As a result the caller continues executing the remaining workflow, even when the benchmark events persistence has failed. Post workflow analysis cannot be done without events.

The fix throws a custom error corresponding to events and lets the caller decide if the processing should continue. As of now the error should result in termination of the workload and cause any unit tests to fail.

Fixes #48

### CODE REVIEW

File: src/main/java/com/microsoft/lst_bench/telemetry/JDBCTelemetryRegistry.java [hunk 1]
```diff
@@ -109,7 +109,8 @@ public void flush() {
       eventsStream = Collections.synchronizedList(new ArrayList<>());
       LOGGER.info("Events flushed to database.");
     } catch (SQLException e) {
-      LOGGER.error("Error while flushing events to database", e);
+      LOGGER.error("Error while flushing events to database");
```
Comment (jcamachor) [inline src/main/java/com/microsoft/lst_bench/telemetry/JDBCTelemetryRegistry.java:112]: Nit. Maybe keep passing the exception to the logger so the stacktrace is printed; having complete information in the log makes debugging easier.

**Review by jcamachor — APPROVED** [review]
Left minor feedback, +1.

Could we test it with the PR where tests passed and was not supposed to? Thanks

File: src/main/java/com/microsoft/lst_bench/telemetry/JDBCTelemetryRegistry.java (hunk 1 above)
Comment (ashvina) [reply src/main/java/com/microsoft/lst_bench/telemetry/JDBCTelemetryRegistry.java:112]: Hi @jcamachor. Thanks for the review.
I am following this principle here: "Don’t just Log & Rethrow" [ref](https://belief-driven-design.com/all-you-ever-wanted-to-know-about-java-exceptions-63d838fedb3/)

The reason for not logging the error stack here is log duplication (_The upstream code has no way to know if an exception was already logged. And it might be propagated through multiple frames_).
This method is not taking action actions other than  passing the exception through to its caller. Doing so allows logging the error stack trace at one place where the exception is getting handled and based on the severity that the caller assigns. WDYT?

**Comment by ashvina** [comment]
> Could we test it with the PR where tests passed and was not supposed to?

Exactly my intent. I have blocked the PR in which this was detected first. Once we merge this, validation of that PR should fail. _Thanks_

File: src/main/java/com/microsoft/lst_bench/telemetry/JDBCTelemetryRegistry.java (hunk 1 above)
Comment (jcamachor) [reply src/main/java/com/microsoft/lst_bench/telemetry/JDBCTelemetryRegistry.java:112]: I'm fine either way, that's why I had +1.
But I'd argue that then probably it's better to remove the error log message all together: Having an error message in the logs without enough details to understand what failed is confusing imo.

**Review by jcamachor — APPROVED** [review]
